#pragma once

// this is just an exampe code generated by some llm

#include "art.hpp"

#include <string>

class PlasmaCompute : public Art {
public:
    std::string about() const override
    {
        return "History and provenance\n"
               "The header describes this implementation as example code generated by an LLM. It does not "
               "identify a model, author, creation date, or a particular upstream project, so those details are "
               "unknown. This is a modern shader example of the traditional plasma visual effect; the available "
               "source does not establish a connection to an archived XScreenSaver hack.\n"
               "\n"
               "Algorithm\n"
               "A compute-shader invocation calculates the color of each pixel directly, without carrying image "
               "state from previous frames. Pixel coordinates are normalized independently by image width and "
               "height to give uv coordinates. Four oscillating scalar fields are added: a horizontal sine wave, "
               "a vertical sine wave, a diagonal wave based on x + y, and a radial wave based on sqrt(x*x + "
               "y*y). Their different spatial frequencies and time multipliers keep the interference from moving "
               "as a single rigid pattern. The radial term is measured from the normalized coordinate origin "
               "rather than from the center of the picture.\n"
               "\n"
               "A fifth contribution is two-dimensional simplex noise. It skews the input into a triangular "
               "lattice, hashes lattice corners, forms gradient contributions, and weights them by distance "
               "before summing. The noise input moves slowly with time, and its contribution is scaled by 0.3, "
               "adding irregularity to the otherwise periodic waves. The combined sum is divided by five and "
               "remapped from signed values toward the interval used by the palette. The selected colormap then "
               "converts that scalar into RGBA, which is written to the output texture.\n"
               "\n"
               "Speed multiplies time in both the waves and noise: zero freezes the procedural field. Scale "
               "multiplies their spatial frequencies, so increasing it makes finer, more numerous features. "
               "Because x and y are normalized separately, changing aspect ratio can stretch the displayed "
               "structures. Palette selection changes the scalar-to-color mapping and recompiles the combined "
               "shader. The flowing appearance comes from interference and noise, rather than a simulated fluid "
               "or a feedback diffusion process.\n"
               "\n"
               "References\n"
               "https://en.wikipedia.org/wiki/Plasma_effect\n"
               "https://en.wikipedia.org/wiki/Simplex_noise\n"
               "https://en.wikipedia.org/wiki/Procedural_texture";
    }

    PlasmaCompute();

private:
    virtual bool render_gui() override;
    virtual void resize(int _w, int _h) override;
    virtual bool render(uint32_t *p) override;
    
    void init_shader();
    void update_uniform_callback();

    // Shader parameters
    float speed = 1.0f;
    float scale = 3.0f;

    std::string current_colormap_name;
    
    // Compute shader base source (without colormap)
    static const char* plasma_compute_shader_base;
};
